// GENERATED by scripts/image-variants.mjs — do not edit by hand.
//
// Maps an image's public path to its natural width and the widths that exist
// beside it as `<stem>-<width>.webp`. `ui/Image` turns this into a `srcset`;
// anything not listed here renders as a plain `<img>` (`SUGGESTION-012`).
export const imageVariants: Record<string, { w: number; v: number[] }> = {
  "/images/afono-cart.webp": {
    "w": 768,
    "v": [
      400,
      640
    ]
  },
  "/images/afono-city-series.webp": {
    "w": 1600,
    "v": [
      400,
      640,
      960,
      1280
    ]
  },
  "/images/afono-colour-palette.webp": {
    "w": 1190,
    "v": [
      400,
      640,
      960
    ]
  },
  "/images/afono-colour-system.webp": {
    "w": 1228,
    "v": [
      400,
      640,
      960
    ]
  },
  "/images/afono-components-content.webp": {
    "w": 1600,
    "v": [
      400,
      640,
      960,
      1280
    ]
  },
  "/images/afono-components-nav.webp": {
    "w": 1600,
    "v": [
      400,
      640,
      960,
      1280
    ]
  },
  "/images/afono-components.webp": {
    "w": 1600,
    "v": [
      400,
      640,
      960,
      1280
    ]
  },
  "/images/afono-landing-page.webp": {
    "w": 1600,
    "v": [
      400,
      640,
      960,
      1280
    ]
  },
  "/images/afono-logo-lockups.webp": {
    "w": 1160,
    "v": [
      400,
      640,
      960
    ]
  },
  "/images/afono-logo-sketches.webp": {
    "w": 1042,
    "v": [
      400,
      640
    ]
  },
  "/images/afono-moodboard.webp": {
    "w": 595,
    "v": [
      400
    ]
  },
  "/images/afono-presentation.webp": {
    "w": 1600,
    "v": [
      400,
      640,
      960,
      1280
    ]
  },
  "/images/afono-print-artwork.webp": {
    "w": 1162,
    "v": [
      400,
      640,
      960
    ]
  },
  "/images/afono-print-development.webp": {
    "w": 1164,
    "v": [
      400,
      640,
      960
    ]
  },
  "/images/afono-print-himal.webp": {
    "w": 1208,
    "v": [
      400,
      640,
      960
    ]
  },
  "/images/afono-print-mask.webp": {
    "w": 1344,
    "v": [
      400,
      640,
      960
    ]
  },
  "/images/afono-print-sketches.webp": {
    "w": 1282,
    "v": [
      400,
      640,
      960
    ]
  },
  "/images/afono-print-wordmark.webp": {
    "w": 1040,
    "v": [
      400,
      640
    ]
  },
  "/images/afono-product-page.webp": {
    "w": 1600,
    "v": [
      400,
      640,
      960,
      1280
    ]
  },
  "/images/afono-prototype.webp": {
    "w": 1600,
    "v": [
      400,
      640,
      960,
      1280
    ]
  },
  "/images/afono-register-page.webp": {
    "w": 1600,
    "v": [
      400,
      640,
      960,
      1280
    ]
  },
  "/images/afono-size-finder.webp": {
    "w": 896,
    "v": [
      400,
      640
    ]
  },
  "/images/afono-social-grid.webp": {
    "w": 476,
    "v": [
      400
    ]
  },
  "/images/afono-social-system.webp": {
    "w": 800,
    "v": [
      400,
      640
    ]
  },
  "/images/afono-tee-mockups-dark.webp": {
    "w": 1274,
    "v": [
      400,
      640,
      960
    ]
  },
  "/images/afono-tee-mockups.webp": {
    "w": 1274,
    "v": [
      400,
      640,
      960
    ]
  },
  "/images/afono-typography.webp": {
    "w": 1226,
    "v": [
      400,
      640,
      960
    ]
  },
  "/images/afono-wordmark-studies.webp": {
    "w": 1140,
    "v": [
      400,
      640,
      960
    ]
  },
  "/images/alexsha_photo-mrx9hbwx-nif2.png": {
    "w": 1720,
    "v": [
      400,
      640,
      960,
      1280
    ]
  },
  "/images/hero-afono.webp": {
    "w": 1600,
    "v": [
      400,
      640,
      960,
      1280
    ]
  },
  "/images/hero-barrier-free-kitchen.webp": {
    "w": 2000,
    "v": [
      400,
      640,
      960,
      1280,
      1600
    ]
  },
  "/images/hero-qis-portal.webp": {
    "w": 1900,
    "v": [
      400,
      640,
      960,
      1280,
      1600
    ]
  },
  "/images/hero-surugami.webp": {
    "w": 1900,
    "v": [
      400,
      640,
      960,
      1280,
      1600
    ]
  },
  "/images/hero-sync-fm.webp": {
    "w": 1578,
    "v": [
      400,
      640,
      960,
      1280
    ]
  },
  "/images/hero-wikimind.webp": {
    "w": 1900,
    "v": [
      400,
      640,
      960,
      1280,
      1600
    ]
  },
  "/images/kitchen-3d-structure.webp": {
    "w": 1600,
    "v": [
      400,
      640,
      960,
      1280
    ]
  },
  "/images/kitchen-journey-map.webp": {
    "w": 1600,
    "v": [
      400,
      640,
      960,
      1280
    ]
  },
  "/images/kitchen-lego-annotated.webp": {
    "w": 1600,
    "v": [
      400,
      640,
      960,
      1280
    ]
  },
  "/images/kitchen-lego.webp": {
    "w": 1600,
    "v": [
      400,
      640,
      960,
      1280
    ]
  },
  "/images/kitchen-observation-fridge.webp": {
    "w": 1600,
    "v": [
      400,
      640,
      960,
      1280
    ]
  },
  "/images/kitchen-observation.webp": {
    "w": 1600,
    "v": [
      400,
      640,
      960,
      1280
    ]
  },
  "/images/kitchen-paper-containers.webp": {
    "w": 1600,
    "v": [
      400,
      640,
      960,
      1280
    ]
  },
  "/images/kitchen-paper-details.webp": {
    "w": 1600,
    "v": [
      400,
      640,
      960,
      1280
    ]
  },
  "/images/kitchen-paper-prototype.webp": {
    "w": 1600,
    "v": [
      400,
      640,
      960,
      1280
    ]
  },
  "/images/kitchen-reach-study.webp": {
    "w": 1600,
    "v": [
      400,
      640,
      960,
      1280
    ]
  },
  "/images/kitchen-simulation.webp": {
    "w": 1600,
    "v": [
      400,
      640,
      960,
      1280
    ]
  },
  "/images/kitchen-wooden-blocks.webp": {
    "w": 1600,
    "v": [
      400,
      640,
      960,
      1280
    ]
  },
  "/images/qis-original-exams.webp": {
    "w": 876,
    "v": [
      400,
      640
    ]
  },
  "/images/qis-original-login.webp": {
    "w": 880,
    "v": [
      400,
      640
    ]
  },
  "/images/qis-original-overview.webp": {
    "w": 1194,
    "v": [
      400,
      640,
      960
    ]
  },
  "/images/qis-structure-14.webp": {
    "w": 1600,
    "v": [
      400,
      640,
      960,
      1280
    ]
  },
  "/images/qis-structure-21.webp": {
    "w": 1600,
    "v": [
      400,
      640,
      960,
      1280
    ]
  },
  "/images/qis-sus-chart.webp": {
    "w": 1600,
    "v": [
      400,
      640,
      960,
      1280
    ]
  },
  "/images/surugami-brand-system.webp": {
    "w": 1600,
    "v": [
      400,
      640,
      960,
      1280
    ]
  },
  "/images/surugami-concept-map.webp": {
    "w": 1600,
    "v": [
      400,
      640,
      960,
      1280
    ]
  },
  "/images/surugami-flyer.webp": {
    "w": 1400,
    "v": [
      400,
      640,
      960
    ]
  },
  "/images/surugami-posters.webp": {
    "w": 1600,
    "v": [
      400,
      640,
      960,
      1280
    ]
  },
  "/images/surugami-research-board.webp": {
    "w": 1600,
    "v": [
      400,
      640,
      960,
      1280
    ]
  },
  "/images/surugami-sitemap.webp": {
    "w": 1600,
    "v": [
      400,
      640,
      960,
      1280
    ]
  },
  "/images/surugami-website.webp": {
    "w": 1600,
    "v": [
      400,
      640,
      960,
      1280
    ]
  },
  "/images/surugami-wireframes.webp": {
    "w": 1400,
    "v": [
      400,
      640,
      960
    ]
  },
  "/images/sync-fm-colour.webp": {
    "w": 1600,
    "v": [
      400,
      640,
      960,
      1280
    ]
  },
  "/images/sync-fm-components.webp": {
    "w": 1600,
    "v": [
      400,
      640,
      960,
      1280
    ]
  },
  "/images/sync-fm-final-screens.webp": {
    "w": 1600,
    "v": [
      400,
      640,
      960,
      1280
    ]
  },
  "/images/sync-fm-logo-system.webp": {
    "w": 1600,
    "v": [
      400,
      640,
      960,
      1280
    ]
  },
  "/images/sync-fm-personas.webp": {
    "w": 1600,
    "v": [
      400,
      640,
      960,
      1280
    ]
  },
  "/images/sync-fm-typography.webp": {
    "w": 1600,
    "v": [
      400,
      640,
      960,
      1280
    ]
  },
  "/images/sync-fm-wireframes.webp": {
    "w": 820,
    "v": [
      400,
      640
    ]
  },
  "/images/tile-afono-brand.webp": {
    "w": 900,
    "v": [
      400,
      640
    ]
  },
  "/images/tile-kitchen-inclusive.webp": {
    "w": 1100,
    "v": [
      400,
      640
    ]
  },
  "/images/tile-qis-product.webp": {
    "w": 700,
    "v": [
      400
    ]
  },
  "/images/tile-qis-research.webp": {
    "w": 1300,
    "v": [
      400,
      640,
      960
    ]
  },
  "/images/tile-surugami-brand.webp": {
    "w": 900,
    "v": [
      400,
      640
    ]
  },
  "/images/tile-surugami-poster.webp": {
    "w": 1600,
    "v": [
      400,
      640,
      960,
      1280
    ]
  },
  "/images/tile-syncfm-interaction.webp": {
    "w": 900,
    "v": [
      400,
      640
    ]
  },
  "/images/tile-syncfm-mobile.webp": {
    "w": 700,
    "v": [
      400
    ]
  },
  "/images/tile-wikimind-brand.webp": {
    "w": 1300,
    "v": [
      400,
      640,
      960
    ]
  },
  "/images/tile-wikimind-web.webp": {
    "w": 1100,
    "v": [
      400,
      640
    ]
  },
  "/images/wikimind-colour-type.webp": {
    "w": 1600,
    "v": [
      400,
      640,
      960,
      1280
    ]
  },
  "/images/wikimind-components.webp": {
    "w": 1400,
    "v": [
      400,
      640,
      960
    ]
  },
  "/images/wikimind-final-screens.webp": {
    "w": 1600,
    "v": [
      400,
      640,
      960,
      1280
    ]
  },
  "/images/wikimind-initial-sketches.webp": {
    "w": 1200,
    "v": [
      400,
      640,
      960
    ]
  },
  "/images/wikimind-logo-sketch.webp": {
    "w": 1420,
    "v": [
      400,
      640,
      960
    ]
  },
  "/images/wikimind-logo-variants.webp": {
    "w": 1600,
    "v": [
      400,
      640,
      960,
      1280
    ]
  },
  "/images/wikimind-mascot.webp": {
    "w": 1600,
    "v": [
      400,
      640,
      960,
      1280
    ]
  },
  "/images/wikimind-moodboard.webp": {
    "w": 1400,
    "v": [
      400,
      640,
      960
    ]
  },
  "/images/wikimind-persona-01.webp": {
    "w": 1600,
    "v": [
      400,
      640,
      960,
      1280
    ]
  },
  "/images/wikimind-persona-02.webp": {
    "w": 1600,
    "v": [
      400,
      640,
      960,
      1280
    ]
  },
  "/images/wikimind-persona-03.webp": {
    "w": 1600,
    "v": [
      400,
      640,
      960,
      1280
    ]
  },
  "/images/wikimind-sitemap.webp": {
    "w": 1600,
    "v": [
      400,
      640,
      960,
      1280
    ]
  },
  "/images/wikimind-ui-kit.webp": {
    "w": 1600,
    "v": [
      400,
      640,
      960,
      1280
    ]
  },
  "/images/wikimind-wireframes.webp": {
    "w": 1400,
    "v": [
      400,
      640,
      960
    ]
  }
};
