// GENERATED by scripts/image-variants.mjs — do not edit by hand.
//
// Maps an image's public path to its natural width and the widths that exist
// beside it as `<stem>-<width>.webp`. `ui/Image` turns this into a `srcset`;
// anything not listed here renders as a plain `<img>` (`SUGGESTION-012`).
export const imageVariants: Record<string, { w: number; v: number[] }> = {
  "/images/alexsha_photo-mrx9hbwx-nif2.png": {
    "w": 1720,
    "v": [
      400,
      640,
      960,
      1280
    ]
  },
  "/images/chatgpt-image-jul-23-2026-10_31_15-am-ms50alwm-za74.png": {
    "w": 1586,
    "v": [
      400,
      640,
      960,
      1280
    ]
  },
  "/images/hero-afono.webp": {
    "w": 2000,
    "v": [
      400,
      640,
      960,
      1280,
      1600
    ]
  },
  "/images/hero-barrier-free-kitchen.webp": {
    "w": 2000,
    "v": [
      400,
      640,
      960,
      1280,
      1600
    ]
  },
  "/images/hero-qis-portal.webp": {
    "w": 2000,
    "v": [
      400,
      640,
      960,
      1280,
      1600
    ]
  },
  "/images/hero-surugami.webp": {
    "w": 2000,
    "v": [
      400,
      640,
      960,
      1280,
      1600
    ]
  },
  "/images/hero-sync-fm.webp": {
    "w": 2000,
    "v": [
      400,
      640,
      960,
      1280,
      1600
    ]
  },
  "/images/hero-wikimind.webp": {
    "w": 2000,
    "v": [
      400,
      640,
      960,
      1280,
      1600
    ]
  },
  "/images/tile-afono-brand.webp": {
    "w": 900,
    "v": [
      400,
      640
    ]
  },
  "/images/tile-kitchen-inclusive.webp": {
    "w": 1100,
    "v": [
      400,
      640
    ]
  },
  "/images/tile-qis-product.webp": {
    "w": 700,
    "v": [
      400
    ]
  },
  "/images/tile-qis-research.webp": {
    "w": 1300,
    "v": [
      400,
      640,
      960
    ]
  },
  "/images/tile-surugami-brand.webp": {
    "w": 900,
    "v": [
      400,
      640
    ]
  },
  "/images/tile-surugami-poster.webp": {
    "w": 1600,
    "v": [
      400,
      640,
      960,
      1280
    ]
  },
  "/images/tile-syncfm-interaction.webp": {
    "w": 900,
    "v": [
      400,
      640
    ]
  },
  "/images/tile-syncfm-mobile.webp": {
    "w": 700,
    "v": [
      400
    ]
  },
  "/images/tile-wikimind-brand.webp": {
    "w": 1300,
    "v": [
      400,
      640,
      960
    ]
  },
  "/images/tile-wikimind-web.webp": {
    "w": 1100,
    "v": [
      400,
      640
    ]
  },
  "/images/wikimind-colour-type.webp": {
    "w": 900,
    "v": [
      400,
      640
    ]
  },
  "/images/wikimind-final-screens.webp": {
    "w": 1900,
    "v": [
      400,
      640,
      960,
      1280,
      1600
    ]
  },
  "/images/wikimind-interface.webp": {
    "w": 1900,
    "v": [
      400,
      640,
      960,
      1280,
      1600
    ]
  },
  "/images/wikimind-logo-sketch.webp": {
    "w": 1200,
    "v": [
      400,
      640,
      960
    ]
  },
  "/images/wikimind-logo-variants.webp": {
    "w": 600,
    "v": [
      400
    ]
  },
  "/images/wikimind-mascot.webp": {
    "w": 1900,
    "v": [
      400,
      640,
      960,
      1280,
      1600
    ]
  },
  "/images/wikimind-persona-01.webp": {
    "w": 600,
    "v": [
      400
    ]
  },
  "/images/wikimind-persona-02.webp": {
    "w": 600,
    "v": [
      400
    ]
  },
  "/images/wikimind-persona-03.webp": {
    "w": 600,
    "v": [
      400
    ]
  },
  "/images/wikimind-prototype.webp": {
    "w": 1900,
    "v": [
      400,
      640,
      960,
      1280,
      1600
    ]
  },
  "/images/wikimind-sitemap.webp": {
    "w": 1900,
    "v": [
      400,
      640,
      960,
      1280,
      1600
    ]
  },
  "/images/wikimind-ui-kit.webp": {
    "w": 600,
    "v": [
      400
    ]
  }
};
