// GENERATED by scripts/image-variants.mjs — do not edit by hand.
//
// Maps an image's public path to its natural width, the widths that exist
// beside it as `<stem>-<width>.webp`, and `bg` — the median colour of its
// border ring. `ui/Image` turns the widths into a `srcset`; `ui/Media` paints
// `bg` behind a contained image so the mat matches the picture rather than
// being a white slab (`SUGGESTION-012`, `DECISION-025`).
export const imageVariants: Record<string, { w: number; v: number[]; bg: string }> = {
  "/images/afono-cart.webp": {
    "w": 768,
    "v": [
      400,
      640
    ],
    "bg": "#ffffff"
  },
  "/images/afono-city-series.webp": {
    "w": 1600,
    "v": [
      400,
      640,
      960,
      1280
    ],
    "bg": "#8e8f93"
  },
  "/images/afono-colour-palette.webp": {
    "w": 1190,
    "v": [
      400,
      640,
      960
    ],
    "bg": "#f0f9ff"
  },
  "/images/afono-colour-system.webp": {
    "w": 1228,
    "v": [
      400,
      640,
      960
    ],
    "bg": "#ffffff"
  },
  "/images/afono-components-content.webp": {
    "w": 1600,
    "v": [
      400,
      640,
      960,
      1280
    ],
    "bg": "#ffffff"
  },
  "/images/afono-components-nav.webp": {
    "w": 1600,
    "v": [
      400,
      640,
      960,
      1280
    ],
    "bg": "#ebebeb"
  },
  "/images/afono-components.webp": {
    "w": 1600,
    "v": [
      400,
      640,
      960,
      1280
    ],
    "bg": "#ffffff"
  },
  "/images/afono-landing-page.webp": {
    "w": 1600,
    "v": [
      400,
      640,
      960,
      1280
    ],
    "bg": "#5d5451"
  },
  "/images/afono-logo-lockups.webp": {
    "w": 1160,
    "v": [
      400,
      640,
      960
    ],
    "bg": "#ffffff"
  },
  "/images/afono-logo-sketches.webp": {
    "w": 1042,
    "v": [
      400,
      640
    ],
    "bg": "#ffffff"
  },
  "/images/afono-market-analysis.webp": {
    "w": 1800,
    "v": [
      400,
      640,
      960,
      1280
    ],
    "bg": "#ffffff"
  },
  "/images/afono-moodboard.webp": {
    "w": 595,
    "v": [
      400
    ],
    "bg": "#cc4f59"
  },
  "/images/afono-presentation.webp": {
    "w": 1600,
    "v": [
      400,
      640,
      960,
      1280
    ],
    "bg": "#ffffff"
  },
  "/images/afono-print-artwork.webp": {
    "w": 1162,
    "v": [
      400,
      640,
      960
    ],
    "bg": "#ffffff"
  },
  "/images/afono-print-development.webp": {
    "w": 1164,
    "v": [
      400,
      640,
      960
    ],
    "bg": "#ffffff"
  },
  "/images/afono-print-himal.webp": {
    "w": 1208,
    "v": [
      400,
      640,
      960
    ],
    "bg": "#ffffff"
  },
  "/images/afono-print-mask.webp": {
    "w": 1344,
    "v": [
      400,
      640,
      960
    ],
    "bg": "#ffffff"
  },
  "/images/afono-print-sketches.webp": {
    "w": 1282,
    "v": [
      400,
      640,
      960
    ],
    "bg": "#ffffff"
  },
  "/images/afono-print-wordmark.webp": {
    "w": 1040,
    "v": [
      400,
      640
    ],
    "bg": "#ffffff"
  },
  "/images/afono-product-page.webp": {
    "w": 1600,
    "v": [
      400,
      640,
      960,
      1280
    ],
    "bg": "#fefefe"
  },
  "/images/afono-prototype.webp": {
    "w": 1600,
    "v": [
      400,
      640,
      960,
      1280
    ],
    "bg": "#fdfefe"
  },
  "/images/afono-register-page.webp": {
    "w": 1600,
    "v": [
      400,
      640,
      960,
      1280
    ],
    "bg": "#f1f5f9"
  },
  "/images/afono-size-finder.webp": {
    "w": 896,
    "v": [
      400,
      640
    ],
    "bg": "#ffffff"
  },
  "/images/afono-social-grid.webp": {
    "w": 476,
    "v": [
      400
    ],
    "bg": "#f6f6f6"
  },
  "/images/afono-social-system.webp": {
    "w": 800,
    "v": [
      400,
      640
    ],
    "bg": "#c1a2a7"
  },
  "/images/afono-tee-mockups-dark.webp": {
    "w": 1274,
    "v": [
      400,
      640,
      960
    ],
    "bg": "#e3e3e3"
  },
  "/images/afono-tee-mockups.webp": {
    "w": 1274,
    "v": [
      400,
      640,
      960
    ],
    "bg": "#e1e1e1"
  },
  "/images/afono-typography.webp": {
    "w": 1226,
    "v": [
      400,
      640,
      960
    ],
    "bg": "#ffffff"
  },
  "/images/afono-wireframes.webp": {
    "w": 1900,
    "v": [
      400,
      640,
      960,
      1280,
      1600
    ],
    "bg": "#ffffff"
  },
  "/images/afono-wordmark-studies.webp": {
    "w": 1140,
    "v": [
      400,
      640,
      960
    ],
    "bg": "#ffffff"
  },
  "/images/alexsha-portrait-og.jpg": {
    "w": 1200,
    "v": [
      400,
      640,
      960
    ],
    "bg": "#b4b4b4"
  },
  "/images/alexsha-portrait.webp": {
    "w": 1720,
    "v": [
      400,
      640,
      960,
      1280
    ],
    "bg": "#b4b4b4"
  },
  "/images/hero-afono.webp": {
    "w": 1920,
    "v": [
      400,
      640,
      960,
      1280,
      1600
    ],
    "bg": "#f7f4f3"
  },
  "/images/hero-barrier-free-kitchen.webp": {
    "w": 1920,
    "v": [
      400,
      640,
      960,
      1280,
      1600
    ],
    "bg": "#ecf4ef"
  },
  "/images/hero-qis-portal.webp": {
    "w": 1920,
    "v": [
      400,
      640,
      960,
      1280,
      1600
    ],
    "bg": "#fcf4f5"
  },
  "/images/hero-surugami.webp": {
    "w": 1920,
    "v": [
      400,
      640,
      960,
      1280,
      1600
    ],
    "bg": "#fcedef"
  },
  "/images/hero-sync-fm.webp": {
    "w": 1920,
    "v": [
      400,
      640,
      960,
      1280,
      1600
    ],
    "bg": "#f4f0f8"
  },
  "/images/hero-wikimind.webp": {
    "w": 1920,
    "v": [
      400,
      640,
      960,
      1280,
      1600
    ],
    "bg": "#eef1fc"
  },
  "/images/kitchen-3d-structure.webp": {
    "w": 1600,
    "v": [
      400,
      640,
      960,
      1280
    ],
    "bg": "#474543"
  },
  "/images/kitchen-animation-poster.webp": {
    "w": 1024,
    "v": [
      400,
      640
    ],
    "bg": "#a7a7aa"
  },
  "/images/kitchen-journey-map.webp": {
    "w": 1600,
    "v": [
      400,
      640,
      960,
      1280
    ],
    "bg": "#f6f6f2"
  },
  "/images/kitchen-lego-annotated.webp": {
    "w": 1600,
    "v": [
      400,
      640,
      960,
      1280
    ],
    "bg": "#a8aeb7"
  },
  "/images/kitchen-lego.webp": {
    "w": 1600,
    "v": [
      400,
      640,
      960,
      1280
    ],
    "bg": "#bec2c5"
  },
  "/images/kitchen-observation-fridge.webp": {
    "w": 1600,
    "v": [
      400,
      640,
      960,
      1280
    ],
    "bg": "#89786a"
  },
  "/images/kitchen-observation.webp": {
    "w": 1600,
    "v": [
      400,
      640,
      960,
      1280
    ],
    "bg": "#8e8c7f"
  },
  "/images/kitchen-paper-containers.webp": {
    "w": 1600,
    "v": [
      400,
      640,
      960,
      1280
    ],
    "bg": "#f3f3ef"
  },
  "/images/kitchen-paper-details.webp": {
    "w": 1600,
    "v": [
      400,
      640,
      960,
      1280
    ],
    "bg": "#f6f6f2"
  },
  "/images/kitchen-paper-prototype.webp": {
    "w": 1600,
    "v": [
      400,
      640,
      960,
      1280
    ],
    "bg": "#eaeae5"
  },
  "/images/kitchen-reach-study.webp": {
    "w": 1600,
    "v": [
      400,
      640,
      960,
      1280
    ],
    "bg": "#b4b1ac"
  },
  "/images/kitchen-simulation-hob.webp": {
    "w": 920,
    "v": [
      400,
      640
    ],
    "bg": "#7a7b73"
  },
  "/images/kitchen-wooden-blocks.webp": {
    "w": 1600,
    "v": [
      400,
      640,
      960,
      1280
    ],
    "bg": "#9ba0a2"
  },
  "/images/pg-abstract.webp": {
    "w": 1035,
    "v": [
      400,
      640
    ],
    "bg": "#f7f7f7"
  },
  "/images/pg-autumn.webp": {
    "w": 1200,
    "v": [
      400,
      640,
      960
    ],
    "bg": "#b34b2a"
  },
  "/images/pg-bead.webp": {
    "w": 1200,
    "v": [
      400,
      640,
      960
    ],
    "bg": "#484e31"
  },
  "/images/pg-bookcover.webp": {
    "w": 1200,
    "v": [
      400,
      640,
      960
    ],
    "bg": "#c6c9ca"
  },
  "/images/pg-character.webp": {
    "w": 1200,
    "v": [
      400,
      640,
      960
    ],
    "bg": "#ead8ff"
  },
  "/images/pg-clip-explosion.webp": {
    "w": 720,
    "v": [
      400
    ],
    "bg": "#5d6c86"
  },
  "/images/pg-clip-hibi.webp": {
    "w": 640,
    "v": [
      400
    ],
    "bg": "#fbeaed"
  },
  "/images/pg-clip-motorbike.webp": {
    "w": 640,
    "v": [
      400
    ],
    "bg": "#34221b"
  },
  "/images/pg-clip-popup.webp": {
    "w": 720,
    "v": [
      400
    ],
    "bg": "#786433"
  },
  "/images/pg-clip-riona.webp": {
    "w": 720,
    "v": [
      400
    ],
    "bg": "#aaabad"
  },
  "/images/pg-desmark-logo.webp": {
    "w": 1200,
    "v": [
      400,
      640,
      960
    ],
    "bg": "#ffffff"
  },
  "/images/pg-double-portrait.webp": {
    "w": 1200,
    "v": [
      400,
      640,
      960
    ],
    "bg": "#f5d0f3"
  },
  "/images/pg-flyer.webp": {
    "w": 1200,
    "v": [
      400,
      640,
      960
    ],
    "bg": "#8d8a8a"
  },
  "/images/pg-forest.webp": {
    "w": 1200,
    "v": [
      400,
      640,
      960
    ],
    "bg": "#063938"
  },
  "/images/pg-frame-detail.webp": {
    "w": 1200,
    "v": [
      400,
      640,
      960
    ],
    "bg": "#756e74"
  },
  "/images/pg-frame.webp": {
    "w": 1200,
    "v": [
      400,
      640,
      960
    ],
    "bg": "#7b747f"
  },
  "/images/pg-gift-cube.webp": {
    "w": 1200,
    "v": [
      400,
      640,
      960
    ],
    "bg": "#c7d9fb"
  },
  "/images/pg-gift-popup.webp": {
    "w": 1200,
    "v": [
      400,
      640,
      960
    ],
    "bg": "#99979b"
  },
  "/images/pg-group-portrait.webp": {
    "w": 1200,
    "v": [
      400,
      640,
      960
    ],
    "bg": "#ffffff"
  },
  "/images/pg-kalender-cover.webp": {
    "w": 1200,
    "v": [
      400,
      640,
      960
    ],
    "bg": "#ece4e8"
  },
  "/images/pg-kalender-dezember.webp": {
    "w": 1200,
    "v": [
      400,
      640,
      960
    ],
    "bg": "#f4ebe9"
  },
  "/images/pg-kalender-februar.webp": {
    "w": 1200,
    "v": [
      400,
      640,
      960
    ],
    "bg": "#e9e8ef"
  },
  "/images/pg-kalender-juli.webp": {
    "w": 1200,
    "v": [
      400,
      640,
      960
    ],
    "bg": "#e6ecf3"
  },
  "/images/pg-kalender-juni.webp": {
    "w": 1200,
    "v": [
      400,
      640,
      960
    ],
    "bg": "#f4eaf0"
  },
  "/images/pg-kalender-maerz.webp": {
    "w": 1200,
    "v": [
      400,
      640,
      960
    ],
    "bg": "#fbf9ea"
  },
  "/images/pg-kalender-mai.webp": {
    "w": 1200,
    "v": [
      400,
      640,
      960
    ],
    "bg": "#f3f5f9"
  },
  "/images/pg-kalender-oktober.webp": {
    "w": 1200,
    "v": [
      400,
      640,
      960
    ],
    "bg": "#f8f0dc"
  },
  "/images/pg-kalender-september.webp": {
    "w": 1200,
    "v": [
      400,
      640,
      960
    ],
    "bg": "#f5edf4"
  },
  "/images/pg-line-study.webp": {
    "w": 1200,
    "v": [
      400,
      640,
      960
    ],
    "bg": "#ffffff"
  },
  "/images/pg-logo.webp": {
    "w": 803,
    "v": [
      400,
      640
    ],
    "bg": "#ffffff"
  },
  "/images/pg-mindruhe.webp": {
    "w": 1200,
    "v": [
      400,
      640,
      960
    ],
    "bg": "#ffffff"
  },
  "/images/pg-packaging-crisps.webp": {
    "w": 794,
    "v": [
      400,
      640
    ],
    "bg": "#ffffff"
  },
  "/images/pg-packaging-perfume-flat.webp": {
    "w": 1185,
    "v": [
      400,
      640,
      960
    ],
    "bg": "#e8f1ff"
  },
  "/images/pg-packaging-perfume.webp": {
    "w": 656,
    "v": [
      400
    ],
    "bg": "#fdfdfd"
  },
  "/images/pg-painting-blossom.webp": {
    "w": 1200,
    "v": [
      400,
      640,
      960
    ],
    "bg": "#8b969d"
  },
  "/images/pg-painting-framed.webp": {
    "w": 1200,
    "v": [
      400,
      640,
      960
    ],
    "bg": "#ceb5a7"
  },
  "/images/pg-painting-luffy.webp": {
    "w": 1200,
    "v": [
      400,
      640,
      960
    ],
    "bg": "#bc9d85"
  },
  "/images/pg-photo-lowkey.webp": {
    "w": 1200,
    "v": [
      400,
      640,
      960
    ],
    "bg": "#030000"
  },
  "/images/pg-photo-stilllife.webp": {
    "w": 1250,
    "v": [
      400,
      640,
      960
    ],
    "bg": "#000004"
  },
  "/images/pg-portrait.webp": {
    "w": 1200,
    "v": [
      400,
      640,
      960
    ],
    "bg": "#c3e2fe"
  },
  "/images/pg-postcard-1.webp": {
    "w": 1029,
    "v": [
      400,
      640
    ],
    "bg": "#ffffff"
  },
  "/images/pg-poster-hologram.webp": {
    "w": 1200,
    "v": [
      400,
      640,
      960
    ],
    "bg": "#191919"
  },
  "/images/pg-poster-museum.webp": {
    "w": 1200,
    "v": [
      400,
      640,
      960
    ],
    "bg": "#f3f3f3"
  },
  "/images/pg-scooter.webp": {
    "w": 1200,
    "v": [
      400,
      640,
      960
    ],
    "bg": "#e2bcf4"
  },
  "/images/pg-sunset.webp": {
    "w": 1200,
    "v": [
      400,
      640,
      960
    ],
    "bg": "#663d41"
  },
  "/images/pg-typography-posters.webp": {
    "w": 900,
    "v": [
      400,
      640
    ],
    "bg": "#f7f7f7"
  },
  "/images/pg-vtri-banner.webp": {
    "w": 1200,
    "v": [
      400,
      640,
      960
    ],
    "bg": "#887da3"
  },
  "/images/pg-vtri-store.webp": {
    "w": 1200,
    "v": [
      400,
      640,
      960
    ],
    "bg": "#a9a0ca"
  },
  "/images/qis-chart-content-vs-interface-de.webp": {
    "w": 1720,
    "v": [
      400,
      640,
      960,
      1280
    ],
    "bg": "#ffffff"
  },
  "/images/qis-chart-content-vs-interface-en.webp": {
    "w": 1720,
    "v": [
      400,
      640,
      960,
      1280
    ],
    "bg": "#ffffff"
  },
  "/images/qis-chart-low-use-sections-de.webp": {
    "w": 1720,
    "v": [
      400,
      640,
      960,
      1280
    ],
    "bg": "#ffffff"
  },
  "/images/qis-chart-low-use-sections-en.webp": {
    "w": 1720,
    "v": [
      400,
      640,
      960,
      1280
    ],
    "bg": "#ffffff"
  },
  "/images/qis-chart-occasional-use-de.webp": {
    "w": 1720,
    "v": [
      400,
      640,
      960,
      1280
    ],
    "bg": "#ffffff"
  },
  "/images/qis-chart-occasional-use-en.webp": {
    "w": 1720,
    "v": [
      400,
      640,
      960,
      1280
    ],
    "bg": "#ffffff"
  },
  "/images/qis-chart-requested-features-de.webp": {
    "w": 1720,
    "v": [
      400,
      640,
      960,
      1280
    ],
    "bg": "#ffffff"
  },
  "/images/qis-chart-requested-features-en.webp": {
    "w": 1720,
    "v": [
      400,
      640,
      960,
      1280
    ],
    "bg": "#ffffff"
  },
  "/images/qis-design-system.webp": {
    "w": 1600,
    "v": [
      400,
      640,
      960,
      1280
    ],
    "bg": "#ffffff"
  },
  "/images/qis-final-screens.webp": {
    "w": 3200,
    "v": [
      400,
      640,
      960,
      1280,
      1600
    ],
    "bg": "#eeedf0"
  },
  "/images/qis-first-iteration.webp": {
    "w": 2600,
    "v": [
      400,
      640,
      960,
      1280,
      1600
    ],
    "bg": "#ffffff"
  },
  "/images/qis-interaction-flow.webp": {
    "w": 1900,
    "v": [
      400,
      640,
      960,
      1280,
      1600
    ],
    "bg": "#f9f9f9"
  },
  "/images/qis-original-exams.webp": {
    "w": 876,
    "v": [
      400,
      640
    ],
    "bg": "#ffffff"
  },
  "/images/qis-original-login.webp": {
    "w": 880,
    "v": [
      400,
      640
    ],
    "bg": "#ffffff"
  },
  "/images/qis-original-overview.webp": {
    "w": 1194,
    "v": [
      400,
      640,
      960
    ],
    "bg": "#ffffff"
  },
  "/images/qis-paper-prototypes.webp": {
    "w": 1600,
    "v": [
      400,
      640,
      960,
      1280
    ],
    "bg": "#ffffff"
  },
  "/images/qis-structure-14.webp": {
    "w": 1600,
    "v": [
      400,
      640,
      960,
      1280
    ],
    "bg": "#ffffff"
  },
  "/images/qis-structure-21.webp": {
    "w": 1600,
    "v": [
      400,
      640,
      960,
      1280
    ],
    "bg": "#ffffff"
  },
  "/images/qis-sus-chart.webp": {
    "w": 1600,
    "v": [
      400,
      640,
      960,
      1280
    ],
    "bg": "#ffffff"
  },
  "/images/surugami-brand-system.webp": {
    "w": 1600,
    "v": [
      400,
      640,
      960,
      1280
    ],
    "bg": "#feffe8"
  },
  "/images/surugami-concept-map.webp": {
    "w": 1600,
    "v": [
      400,
      640,
      960,
      1280
    ],
    "bg": "#ffffff"
  },
  "/images/surugami-flyer.webp": {
    "w": 1400,
    "v": [
      400,
      640,
      960
    ],
    "bg": "#ffffe6"
  },
  "/images/surugami-posters.webp": {
    "w": 1600,
    "v": [
      400,
      640,
      960,
      1280
    ],
    "bg": "#feffe8"
  },
  "/images/surugami-research-board.webp": {
    "w": 1600,
    "v": [
      400,
      640,
      960,
      1280
    ],
    "bg": "#feffe8"
  },
  "/images/surugami-sitemap.webp": {
    "w": 1600,
    "v": [
      400,
      640,
      960,
      1280
    ],
    "bg": "#ffffff"
  },
  "/images/surugami-website.webp": {
    "w": 1600,
    "v": [
      400,
      640,
      960,
      1280
    ],
    "bg": "#feffe8"
  },
  "/images/surugami-wireframes.webp": {
    "w": 1400,
    "v": [
      400,
      640,
      960
    ],
    "bg": "#feffe8"
  },
  "/images/sync-fm-colour.webp": {
    "w": 1600,
    "v": [
      400,
      640,
      960,
      1280
    ],
    "bg": "#ffffff"
  },
  "/images/sync-fm-components.webp": {
    "w": 1600,
    "v": [
      400,
      640,
      960,
      1280
    ],
    "bg": "#f0edf1"
  },
  "/images/sync-fm-logo-system.webp": {
    "w": 1600,
    "v": [
      400,
      640,
      960,
      1280
    ],
    "bg": "#f0edf1"
  },
  "/images/sync-fm-typography.webp": {
    "w": 1600,
    "v": [
      400,
      640,
      960,
      1280
    ],
    "bg": "#ffffff"
  },
  "/images/sync-fm-wireframes.webp": {
    "w": 820,
    "v": [
      400,
      640
    ],
    "bg": "#ffffff"
  },
  "/images/wikimind-colour-type.webp": {
    "w": 1600,
    "v": [
      400,
      640,
      960,
      1280
    ],
    "bg": "#f4faff"
  },
  "/images/wikimind-components.webp": {
    "w": 1400,
    "v": [
      400,
      640,
      960
    ],
    "bg": "#fefeff"
  },
  "/images/wikimind-final-screens.webp": {
    "w": 1600,
    "v": [
      400,
      640,
      960,
      1280
    ],
    "bg": "#ffffff"
  },
  "/images/wikimind-initial-sketches.webp": {
    "w": 1200,
    "v": [
      400,
      640,
      960
    ],
    "bg": "#ffffff"
  },
  "/images/wikimind-logo-sketch.webp": {
    "w": 1420,
    "v": [
      400,
      640,
      960
    ],
    "bg": "#ffffff"
  },
  "/images/wikimind-logo-variants.webp": {
    "w": 1600,
    "v": [
      400,
      640,
      960,
      1280
    ],
    "bg": "#ffffff"
  },
  "/images/wikimind-mascot.webp": {
    "w": 1600,
    "v": [
      400,
      640,
      960,
      1280
    ],
    "bg": "#fafcff"
  },
  "/images/wikimind-moodboard.webp": {
    "w": 1400,
    "v": [
      400,
      640,
      960
    ],
    "bg": "#f8f8f8"
  },
  "/images/wikimind-sitemap.webp": {
    "w": 1600,
    "v": [
      400,
      640,
      960,
      1280
    ],
    "bg": "#fbfcff"
  },
  "/images/wikimind-ui-kit.webp": {
    "w": 1600,
    "v": [
      400,
      640,
      960,
      1280
    ],
    "bg": "#dae6fb"
  },
  "/images/wikimind-wireframes.webp": {
    "w": 1400,
    "v": [
      400,
      640,
      960
    ],
    "bg": "#f4fafe"
  }
};
